### ISSUE TITLE
Incorrect sha256 in README.md

### ISSUE THREAD

**Issue by cgrindel** [thundergolfer/bazel-mypy-integration#13]
This is a great project. Thanks for putting this together.

I believe that the sha256 value for 0.0.7 which is listed in the README.md is incorrect. I believe that the actual value is `bf7ecd386740328f96c343dca095a63b93df7f86f8d3e1e2e6ff46e400880077`. The corrected 

```
http_archive(
    name = "mypy_integration",
    sha256 = "bf7ecd386740328f96c343dca095a63b93df7f86f8d3e1e2e6ff46e400880077",  # for 0.0.7
    strip_prefix = "bazel-mypy-integration-{version}".format(version = mypy_integration_version),
    url = "https://github.com/thundergolfer/bazel-mypy-integration/archive/{version}.zip".format(
        version = mypy_integration_version,
    ),
)
```

**Comment by thundergolfer** [comment]
Thanks for pointing this out, I'll give it a look now.

**Comment by thundergolfer** [comment]
Thanks 🙂
