### ISSUE TITLE
Add a new release

### ISSUE THREAD

**Issue by mbkroese** [thundergolfer/bazel-mypy-integration#49]
I would like to use the changes added in this pull request so that I can use a newer version of mypy: https://github.com/thundergolfer/bazel-mypy-integration/pull/45

Could you please add a new release?

**Comment by jkaye2012** [comment]
Came here to ask the same!

**Comment by mbkroese** [comment]
@thundergolfer would a new release be possible?

**Comment by alexeagle** [comment]
https://github.com/thundergolfer/bazel-mypy-integration/releases/tag/0.3.0
